# CONFIGURAÇÕES DO ALERTA BET FÁBIO PRO

# Minutos para analisar
FIRST_HALF_START = 25
FIRST_HALF_END = 40

SECOND_HALF_START = 70
SECOND_HALF_END = 85

# Critérios mínimos
MIN_DANGEROUS_ATTACKS_HT = 20
MIN_DANGEROUS_ATTACKS_FT = 50

MIN_SHOTS = 5
MIN_CORNERS = 2

# Gestão
MAX_ENTRIES_PER_GAME = 3
STOP_AFTER_TWO_LOSSES = True
STAKE_PERCENT = 5
